package com.mycompany.triptalk;

import com.google.gson.Gson;
import com.mycompany.triptalk.clases.Pregunta;
import com.mycompany.triptalk.clases.Publicacion;
import com.mycompany.triptalk.clases.Usuario;
import java.awt.Desktop;
import java.awt.GridLayout;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
// excel
import org.apache.poi.ss.usermodel.*;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.apache.poi.xssf.usermodel.XSSFDrawing;
import org.apache.poi.xssf.usermodel.XSSFChart;
import org.apache.poi.ss.util.CellRangeAddress;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xddf.usermodel.chart.XDDFCategoryAxis;
import org.apache.poi.xddf.usermodel.chart.XDDFDataSourcesFactory;
import org.apache.poi.xddf.usermodel.chart.XDDFNumericalDataSource;
import org.apache.poi.xddf.usermodel.chart.XDDFValueAxis;
import org.apache.poi.xddf.usermodel.chart.XDDFBarChartData;
import org.apache.poi.xddf.usermodel.chart.AxisPosition;
import org.apache.poi.xddf.usermodel.chart.BarDirection;
import org.apache.poi.xddf.usermodel.chart.XDDFCategoryDataSource;
import org.apache.poi.xddf.usermodel.chart.ChartTypes;
import java.io.File;
import java.io.FileOutputStream;
//pdf
import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.element.Paragraph;
import com.itextpdf.layout.element.Table;
import java.io.FileNotFoundException;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.stream.Collectors;
//
import org.json.simple.JSONArray;
import org.json.simple.parser.JSONParser;

public class MenuFrame extends javax.swing.JFrame {

    private ArrayList<Usuario> listUsuarios = new ArrayList<>();
    private ArrayList<Publicacion> listPublicaciones = new ArrayList<>();
    private ArrayList<Pregunta> listPreguntas = new ArrayList<>();
    private Usuario usuarioActual;
    private int feedIndex = 0;
    private GridLayout grid = new GridLayout(1, 1);

    private String ruta = "C:\\Users\\arman\\Instituto Tecnológico de Morelia\\DANIEL ADRIAN ROQUE CORTES - Red social de sugerencia de viajes\\Files\\";

    public MenuFrame() {
        initComponents();
        setLocationRelativeTo(null);
    }

    public MenuFrame(Usuario usuarioActual) {
        initComponents();
        setLocationRelativeTo(null);
        this.usuarioActual = usuarioActual;
        panelFeed.setLayout(grid);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new org.edisoncor.gui.panel.Panel();
        jPanel1 = new javax.swing.JPanel();
        logo = new org.edisoncor.gui.panel.PanelImage();
        labelNombre = new javax.swing.JLabel();
        labelApellido = new javax.swing.JLabel();
        btnCerrarSesion = new org.edisoncor.gui.panel.PanelImage();
        jLabel3 = new javax.swing.JLabel();
        btnCrearOpinion = new org.edisoncor.gui.panel.PanelImage();
        jLabel1 = new javax.swing.JLabel();
        btnCrearViaje = new org.edisoncor.gui.panel.PanelImage();
        jLabel2 = new javax.swing.JLabel();
        btnUsuariosPane = new org.edisoncor.gui.panel.PanelImage();
        btnUsuarios = new javax.swing.JLabel();
        btnLugares = new org.edisoncor.gui.panel.PanelImage();
        labelBtnLugaresPopulares = new javax.swing.JLabel();
        btnTopus = new org.edisoncor.gui.panel.PanelImage();
        labelBtnTopUsuarios = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        MenuInicio = new javax.swing.JPanel();
        MenuPrincipal = new org.edisoncor.gui.panel.PanelImage();
        panelImageOpinionBtn = new org.edisoncor.gui.panel.PanelImage();
        btnOpiniones = new javax.swing.JLabel();
        panelImageViajesBtn = new org.edisoncor.gui.panel.PanelImage();
        btnViajes = new javax.swing.JLabel();
        panelImageMisPublicacionesBtn = new org.edisoncor.gui.panel.PanelImage();
        btnMisPublicaciones = new javax.swing.JLabel();
        scrollPrincipal = new javax.swing.JScrollPane();
        panelFeed = new javax.swing.JPanel();
        CrearOpinion = new javax.swing.JPanel();
        panelImage2 = new org.edisoncor.gui.panel.PanelImage();
        jLabel4 = new javax.swing.JLabel();
        panelImage4 = new org.edisoncor.gui.panel.PanelImage();
        panelImage5 = new org.edisoncor.gui.panel.PanelImage();
        jLabel5 = new javax.swing.JLabel();
        txtFieldOPLugar = new javax.swing.JTextField();
        txtFielOPPresupuesto = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        txtFielOPLugar1 = new javax.swing.JTextField();
        txtFielOPLugar2 = new javax.swing.JTextField();
        txtFielOPLugar3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtFielOPObstaculo = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtFielOPEquipaje = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtFielOPFechas = new javax.swing.JTextArea();
        btnAtras = new org.edisoncor.gui.panel.PanelImage();
        panelImage8 = new org.edisoncor.gui.panel.PanelImage();
        jLabel11 = new javax.swing.JLabel();
        CrearViaje = new javax.swing.JPanel();
        panelImage3 = new org.edisoncor.gui.panel.PanelImage();
        jLabel12 = new javax.swing.JLabel();
        panelImage9 = new org.edisoncor.gui.panel.PanelImage();
        panelImage10 = new org.edisoncor.gui.panel.PanelImage();
        jLabel13 = new javax.swing.JLabel();
        txtFieldVILugar = new javax.swing.JTextField();
        txtFieldVICosto = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtFieldVIDetalles = new javax.swing.JTextArea();
        btnAtras1 = new org.edisoncor.gui.panel.PanelImage();
        panelImage11 = new org.edisoncor.gui.panel.PanelImage();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1070, 660));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fondo.setForeground(new java.awt.Color(255, 255, 255));
        fondo.setColorPrimario(new java.awt.Color(246, 252, 251));
        fondo.setColorSecundario(new java.awt.Color(246, 252, 251));
        fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(246, 252, 251));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logoTripTalk.png"))); // NOI18N

        javax.swing.GroupLayout logoLayout = new javax.swing.GroupLayout(logo);
        logo.setLayout(logoLayout);
        logoLayout.setHorizontalGroup(
            logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );
        logoLayout.setVerticalGroup(
            logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );

        jPanel1.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 220, 120));

        labelNombre.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNombre.setText("NOMBRE NAME");
        jPanel1.add(labelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 200, 50));

        labelApellido.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelApellido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelApellido.setText("APELLIDOS");
        jPanel1.add(labelApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 200, 50));

        btnCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botonBlancoSombra.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 173, 172));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Cerrar Sesión");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnCerrarSesionLayout = new javax.swing.GroupLayout(btnCerrarSesion);
        btnCerrarSesion.setLayout(btnCerrarSesionLayout);
        btnCerrarSesionLayout.setHorizontalGroup(
            btnCerrarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        btnCerrarSesionLayout.setVerticalGroup(
            btnCerrarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 600, 200, 50));

        btnCrearOpinion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/barraNaranja.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Crear Opinión");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnCrearOpinionLayout = new javax.swing.GroupLayout(btnCrearOpinion);
        btnCrearOpinion.setLayout(btnCrearOpinionLayout);
        btnCrearOpinionLayout.setHorizontalGroup(
            btnCrearOpinionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
        );
        btnCrearOpinionLayout.setVerticalGroup(
            btnCrearOpinionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCrearOpinionLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(btnCrearOpinion, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 290, 190, 50));

        btnCrearViaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/barraNaranja.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Ofrecer Viaje");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnCrearViajeLayout = new javax.swing.GroupLayout(btnCrearViaje);
        btnCrearViaje.setLayout(btnCrearViajeLayout);
        btnCrearViajeLayout.setHorizontalGroup(
            btnCrearViajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
        );
        btnCrearViajeLayout.setVerticalGroup(
            btnCrearViajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(btnCrearViaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 350, -1, -1));

        btnUsuariosPane.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/barraNaranja.png"))); // NOI18N

        btnUsuarios.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        btnUsuarios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnUsuarios.setText("Ver usuarios");
        btnUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUsuariosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnUsuariosPaneLayout = new javax.swing.GroupLayout(btnUsuariosPane);
        btnUsuariosPane.setLayout(btnUsuariosPaneLayout);
        btnUsuariosPaneLayout.setHorizontalGroup(
            btnUsuariosPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnUsuarios, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
        );
        btnUsuariosPaneLayout.setVerticalGroup(
            btnUsuariosPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(btnUsuariosPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 410, -1, -1));

        btnLugares.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botonBlancoSombra.png"))); // NOI18N

        labelBtnLugaresPopulares.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        labelBtnLugaresPopulares.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelBtnLugaresPopulares.setText("Lugares más populares");
        labelBtnLugaresPopulares.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelBtnLugaresPopulares.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelBtnLugaresPopularesMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnLugaresLayout = new javax.swing.GroupLayout(btnLugares);
        btnLugares.setLayout(btnLugaresLayout);
        btnLugaresLayout.setHorizontalGroup(
            btnLugaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnLugaresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelBtnLugaresPopulares, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnLugaresLayout.setVerticalGroup(
            btnLugaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelBtnLugaresPopulares, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(btnLugares, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, 140, 30));

        btnTopus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botonBlancoSombra.png"))); // NOI18N

        labelBtnTopUsuarios.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        labelBtnTopUsuarios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelBtnTopUsuarios.setText("Top usuarios");
        labelBtnTopUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelBtnTopUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelBtnTopUsuariosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnTopusLayout = new javax.swing.GroupLayout(btnTopus);
        btnTopus.setLayout(btnTopusLayout);
        btnTopusLayout.setHorizontalGroup(
            btnTopusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnTopusLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelBtnTopUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnTopusLayout.setVerticalGroup(
            btnTopusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelBtnTopUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(btnTopus, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 550, 140, 30));

        fondo.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 660));

        jTabbedPane1.setBackground(new java.awt.Color(246, 252, 251));
        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        MenuInicio.setBackground(new java.awt.Color(246, 252, 251));

        MenuPrincipal.setBackground(new java.awt.Color(246, 252, 251));
        MenuPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/panelBlancoRedondeado.png"))); // NOI18N
        MenuPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelImageOpinionBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botonGrisSombra.png"))); // NOI18N

        btnOpiniones.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnOpiniones.setForeground(new java.awt.Color(102, 102, 102));
        btnOpiniones.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnOpiniones.setText("Opiniones");
        btnOpiniones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnOpiniones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnOpinionesMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelImageOpinionBtnLayout = new javax.swing.GroupLayout(panelImageOpinionBtn);
        panelImageOpinionBtn.setLayout(panelImageOpinionBtnLayout);
        panelImageOpinionBtnLayout.setHorizontalGroup(
            panelImageOpinionBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnOpiniones, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );
        panelImageOpinionBtnLayout.setVerticalGroup(
            panelImageOpinionBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnOpiniones, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        MenuPrincipal.add(panelImageOpinionBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 140, 40));

        panelImageViajesBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botonBlancoSombra.png"))); // NOI18N

        btnViajes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnViajes.setForeground(new java.awt.Color(102, 102, 102));
        btnViajes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnViajes.setText("Viajes");
        btnViajes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnViajes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnViajesMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelImageViajesBtnLayout = new javax.swing.GroupLayout(panelImageViajesBtn);
        panelImageViajesBtn.setLayout(panelImageViajesBtnLayout);
        panelImageViajesBtnLayout.setHorizontalGroup(
            panelImageViajesBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnViajes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );
        panelImageViajesBtnLayout.setVerticalGroup(
            panelImageViajesBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnViajes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        MenuPrincipal.add(panelImageViajesBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 140, 40));

        panelImageMisPublicacionesBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botonBlancoSombra.png"))); // NOI18N

        btnMisPublicaciones.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnMisPublicaciones.setForeground(new java.awt.Color(102, 102, 102));
        btnMisPublicaciones.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnMisPublicaciones.setText("Mis publicaciones");
        btnMisPublicaciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMisPublicaciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMisPublicacionesMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelImageMisPublicacionesBtnLayout = new javax.swing.GroupLayout(panelImageMisPublicacionesBtn);
        panelImageMisPublicacionesBtn.setLayout(panelImageMisPublicacionesBtnLayout);
        panelImageMisPublicacionesBtnLayout.setHorizontalGroup(
            panelImageMisPublicacionesBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnMisPublicaciones, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );
        panelImageMisPublicacionesBtnLayout.setVerticalGroup(
            panelImageMisPublicacionesBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnMisPublicaciones, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        MenuPrincipal.add(panelImageMisPublicacionesBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 140, 40));

        scrollPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        scrollPrincipal.setBorder(null);
        scrollPrincipal.setForeground(new java.awt.Color(255, 255, 255));

        panelFeed.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelFeedLayout = new javax.swing.GroupLayout(panelFeed);
        panelFeed.setLayout(panelFeedLayout);
        panelFeedLayout.setHorizontalGroup(
            panelFeedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        panelFeedLayout.setVerticalGroup(
            panelFeedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );

        scrollPrincipal.setViewportView(panelFeed);

        MenuPrincipal.add(scrollPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 800, 540));

        javax.swing.GroupLayout MenuInicioLayout = new javax.swing.GroupLayout(MenuInicio);
        MenuInicio.setLayout(MenuInicioLayout);
        MenuInicioLayout.setHorizontalGroup(
            MenuInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 868, Short.MAX_VALUE)
            .addGroup(MenuInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(MenuInicioLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(MenuPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 857, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        MenuInicioLayout.setVerticalGroup(
            MenuInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
            .addGroup(MenuInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(MenuInicioLayout.createSequentialGroup()
                    .addGap(0, 5, Short.MAX_VALUE)
                    .addComponent(MenuPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 5, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("tab5", MenuInicio);

        CrearOpinion.setBackground(new java.awt.Color(246, 252, 251));

        panelImage2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/panelBlancoRedondeado.png"))); // NOI18N
        panelImage2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("OPINA SOBRE UN LUGAR");
        panelImage2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 490, 50));

        panelImage4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/barraNaranja.png"))); // NOI18N

        javax.swing.GroupLayout panelImage4Layout = new javax.swing.GroupLayout(panelImage4);
        panelImage4.setLayout(panelImage4Layout);
        panelImage4Layout.setHorizontalGroup(
            panelImage4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelImage4Layout.setVerticalGroup(
            panelImage4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        panelImage2.add(panelImage4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, 280, 50));

        panelImage5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/barraNaranja.png"))); // NOI18N

        javax.swing.GroupLayout panelImage5Layout = new javax.swing.GroupLayout(panelImage5);
        panelImage5.setLayout(panelImage5Layout);
        panelImage5Layout.setHorizontalGroup(
            panelImage5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );
        panelImage5Layout.setVerticalGroup(
            panelImage5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        panelImage2.add(panelImage5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 320, 50));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(189, 75, 0));
        jLabel5.setText("¿Qué lugar visitaste?");
        panelImage2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 150, -1));

        txtFieldOPLugar.setBackground(new java.awt.Color(255, 240, 222));
        txtFieldOPLugar.setToolTipText("Escribe el nombre del lugar");
        panelImage2.add(txtFieldOPLugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 740, -1));

        txtFielOPPresupuesto.setBackground(new java.awt.Color(255, 240, 222));
        txtFielOPPresupuesto.setToolTipText("Escribe una cantidad");
        panelImage2.add(txtFielOPPresupuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 150, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(189, 75, 0));
        jLabel6.setText("¿Qué presupuesto recomiendas para visitar este lugar?");
        panelImage2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 410, -1));
        panelImage2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 263, 760, 10));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(189, 75, 0));
        jLabel7.setText("Principal obstáculo durante el viaje");
        panelImage2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 290, -1));

        txtFielOPLugar1.setBackground(new java.awt.Color(255, 240, 222));
        panelImage2.add(txtFielOPLugar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 230, -1));

        txtFielOPLugar2.setBackground(new java.awt.Color(255, 240, 222));
        panelImage2.add(txtFielOPLugar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, 270, -1));

        txtFielOPLugar3.setBackground(new java.awt.Color(255, 240, 222));
        panelImage2.add(txtFielOPLugar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 310, 230, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(189, 75, 0));
        jLabel8.setText("Recomienda tres sitios para visitar al hacer este viaje ");
        panelImage2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, -1, -1));

        txtFielOPObstaculo.setBackground(new java.awt.Color(255, 240, 222));
        txtFielOPObstaculo.setColumns(20);
        txtFielOPObstaculo.setRows(5);
        jScrollPane1.setViewportView(txtFielOPObstaculo);

        panelImage2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 350, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(189, 75, 0));
        jLabel9.setText("¿Qué recomiendas llevar en el equipaje?");
        panelImage2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 360, 290, -1));

        txtFielOPEquipaje.setBackground(new java.awt.Color(255, 240, 222));
        txtFielOPEquipaje.setColumns(20);
        txtFielOPEquipaje.setRows(5);
        jScrollPane2.setViewportView(txtFielOPEquipaje);

        panelImage2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 390, 340, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(189, 75, 0));
        jLabel10.setText("Mejores fechas para este viaje");
        panelImage2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 500, 290, -1));

        txtFielOPFechas.setBackground(new java.awt.Color(255, 240, 222));
        txtFielOPFechas.setColumns(20);
        txtFielOPFechas.setRows(5);
        jScrollPane3.setViewportView(txtFielOPFechas);

        panelImage2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 530, 350, 90));

        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.png"))); // NOI18N
        btnAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAtrasMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnAtrasLayout = new javax.swing.GroupLayout(btnAtras);
        btnAtras.setLayout(btnAtrasLayout);
        btnAtrasLayout.setHorizontalGroup(
            btnAtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        btnAtrasLayout.setVerticalGroup(
            btnAtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        panelImage2.add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 70, 70));

        panelImage8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/barraNaranja.png"))); // NOI18N

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Publicar");
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelImage8Layout = new javax.swing.GroupLayout(panelImage8);
        panelImage8.setLayout(panelImage8Layout);
        panelImage8Layout.setHorizontalGroup(
            panelImage8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        panelImage8Layout.setVerticalGroup(
            panelImage8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        panelImage2.add(panelImage8, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 550, 130, 50));

        javax.swing.GroupLayout CrearOpinionLayout = new javax.swing.GroupLayout(CrearOpinion);
        CrearOpinion.setLayout(CrearOpinionLayout);
        CrearOpinionLayout.setHorizontalGroup(
            CrearOpinionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImage2, javax.swing.GroupLayout.DEFAULT_SIZE, 868, Short.MAX_VALUE)
        );
        CrearOpinionLayout.setVerticalGroup(
            CrearOpinionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CrearOpinionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelImage2, javax.swing.GroupLayout.DEFAULT_SIZE, 664, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab2", CrearOpinion);

        CrearViaje.setBackground(new java.awt.Color(246, 252, 251));

        panelImage3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/panelBlancoRedondeado.png"))); // NOI18N
        panelImage3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("OFRECE UN VIAJE");
        panelImage3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 490, 50));

        panelImage9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/barraNaranja.png"))); // NOI18N

        javax.swing.GroupLayout panelImage9Layout = new javax.swing.GroupLayout(panelImage9);
        panelImage9.setLayout(panelImage9Layout);
        panelImage9Layout.setHorizontalGroup(
            panelImage9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelImage9Layout.setVerticalGroup(
            panelImage9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        panelImage3.add(panelImage9, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, 280, 50));

        panelImage10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/barraNaranja.png"))); // NOI18N

        javax.swing.GroupLayout panelImage10Layout = new javax.swing.GroupLayout(panelImage10);
        panelImage10.setLayout(panelImage10Layout);
        panelImage10Layout.setHorizontalGroup(
            panelImage10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelImage10Layout.setVerticalGroup(
            panelImage10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        panelImage3.add(panelImage10, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 320, 50));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(189, 75, 0));
        jLabel13.setText("Lugar");
        panelImage3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 150, -1));

        txtFieldVILugar.setBackground(new java.awt.Color(255, 240, 222));
        txtFieldVILugar.setToolTipText("Escribe el nombre del lugar");
        panelImage3.add(txtFieldVILugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 750, -1));

        txtFieldVICosto.setBackground(new java.awt.Color(255, 240, 222));
        txtFieldVICosto.setToolTipText("Escribe una cantidad");
        panelImage3.add(txtFieldVICosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 180, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(189, 75, 0));
        jLabel14.setText("Costo del viaje");
        panelImage3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 410, -1));
        panelImage3.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 760, 10));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(189, 75, 0));
        jLabel15.setText("Detalles extra del viaje");
        panelImage3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 690, -1));

        txtFieldVIDetalles.setBackground(new java.awt.Color(255, 240, 222));
        txtFieldVIDetalles.setColumns(20);
        txtFieldVIDetalles.setRows(5);
        jScrollPane4.setViewportView(txtFieldVIDetalles);

        panelImage3.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 750, -1));

        btnAtras1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.png"))); // NOI18N
        btnAtras1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAtras1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnAtras1Layout = new javax.swing.GroupLayout(btnAtras1);
        btnAtras1.setLayout(btnAtras1Layout);
        btnAtras1Layout.setHorizontalGroup(
            btnAtras1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        btnAtras1Layout.setVerticalGroup(
            btnAtras1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        panelImage3.add(btnAtras1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 70, 70));

        panelImage11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/barraNaranja.png"))); // NOI18N

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Publicar");
        jLabel16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelImage11Layout = new javax.swing.GroupLayout(panelImage11);
        panelImage11.setLayout(panelImage11Layout);
        panelImage11Layout.setHorizontalGroup(
            panelImage11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        panelImage11Layout.setVerticalGroup(
            panelImage11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        panelImage3.add(panelImage11, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 550, 130, 50));

        javax.swing.GroupLayout CrearViajeLayout = new javax.swing.GroupLayout(CrearViaje);
        CrearViaje.setLayout(CrearViajeLayout);
        CrearViajeLayout.setHorizontalGroup(
            CrearViajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CrearViajeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelImage3, javax.swing.GroupLayout.DEFAULT_SIZE, 856, Short.MAX_VALUE)
                .addContainerGap())
        );
        CrearViajeLayout.setVerticalGroup(
            CrearViajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CrearViajeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelImage3, javax.swing.GroupLayout.DEFAULT_SIZE, 664, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab3", CrearViaje);

        fondo.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, -9, 920, 670));

        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        //CREAR PUBLICACION
        LimpiarCrearOpinion();
        jTabbedPane1.setSelectedIndex(1);

    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        //OFRECER VIAJE
        LimpiarCrearViaje();
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void btnAtras1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAtras1MouseClicked
        LimpiarCrearOpinion();
        LimpiarCrearViaje();
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_btnAtras1MouseClicked

    private void btnAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAtrasMouseClicked
        LimpiarCrearOpinion();
        LimpiarCrearViaje();
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_btnAtrasMouseClicked

    private void btnOpinionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOpinionesMouseClicked
        // MOSTRAR TODAS LAS OPINIONES
        feedIndex = 0;
        panelImageOpinionBtn.setIcon(new ImageIcon(getClass().getResource("/images/botonGrisSombra.png")));
        panelImageViajesBtn.setIcon(new ImageIcon(getClass().getResource("/images/botonBlancoSombra.png")));
        panelImageMisPublicacionesBtn.setIcon(new ImageIcon(getClass().getResource("/images/botonBlancoSombra.png")));
        fondo.updateUI();
        ActualizarFeed();
    }//GEN-LAST:event_btnOpinionesMouseClicked

    private void btnViajesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViajesMouseClicked
        // MOSTRAR VIAJES OFRECIDOS POR ADMIN
        feedIndex = 1;
        panelImageOpinionBtn.setIcon(new ImageIcon(getClass().getResource("/images/botonBlancoSombra.png")));
        panelImageViajesBtn.setIcon(new ImageIcon(getClass().getResource("/images/botonGrisSombra.png")));
        panelImageMisPublicacionesBtn.setIcon(new ImageIcon(getClass().getResource("/images/botonBlancoSombra.png")));
        fondo.updateUI();
        ActualizarFeed();
    }//GEN-LAST:event_btnViajesMouseClicked

    private void btnMisPublicacionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMisPublicacionesMouseClicked
        // MOSTRAR MIS PUBLICACIONES
        feedIndex = 2;
        panelImageOpinionBtn.setIcon(new ImageIcon(getClass().getResource("/images/botonBlancoSombra.png")));
        panelImageViajesBtn.setIcon(new ImageIcon(getClass().getResource("/images/botonBlancoSombra.png")));
        panelImageMisPublicacionesBtn.setIcon(new ImageIcon(getClass().getResource("/images/botonGrisSombra.png")));
        fondo.updateUI();
        ActualizarFeed();
    }//GEN-LAST:event_btnMisPublicacionesMouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // Cerrar sesión
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // Cerrar MENU
        GuardarPublicaciones();
        new LoginFrame().setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // FRAME SE ABRE
        CargarUsuarios();
        CargarPublicaciones();
        labelNombre.setText(usuarioActual.getNombre());
        labelApellido.setText(usuarioActual.getApellido());

        //SI NO ES ADMIN, ocultar ofrecer viaje y ver usuarios
        if (usuarioActual.getRol().equalsIgnoreCase("npc")) {
            btnCrearViaje.setVisible(false); //boton
            btnUsuariosPane.setVisible(false);
            btnUsuarios.setVisible(false);
            jTabbedPane1.remove(2); //pestaña para crear viajes
            btnTopus.setVisible(false);
            btnLugares.setVisible(false);
        }
        ActualizarFeed();

    }//GEN-LAST:event_formWindowOpened

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // Publicar Opinion
        if (txtFieldOPLugar.getText().trim().isEmpty()
                || txtFielOPEquipaje.getText().trim().isEmpty()
                || txtFielOPLugar1.getText().trim().isEmpty()
                || txtFielOPLugar2.getText().trim().isEmpty()
                || txtFielOPLugar3.getText().trim().isEmpty()
                || txtFielOPObstaculo.getText().trim().isEmpty()
                || txtFielOPPresupuesto.getText().trim().isEmpty()
                || txtFielOPFechas.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "¡Debes rellenar todos los campos!");
        } else {
            int id;
            if (listPublicaciones.isEmpty()) {
                id = listPublicaciones.size();
            } else {
                id = listPublicaciones.getLast().getIdPublicacion() + 1;
            }
            Publicacion publicacion = new Publicacion(
                    id,
                    usuarioActual.getIdUsuario(),
                    txtFieldOPLugar.getText(),
                    txtFielOPPresupuesto.getText(),
                    txtFielOPObstaculo.getText(),
                    txtFielOPLugar1.getText(), // lugar recomendado 1
                    txtFielOPLugar2.getText(), // lugar recomendado 2
                    txtFielOPLugar3.getText(), // lugar recomendado 3
                    txtFielOPEquipaje.getText(),
                    txtFielOPFechas.getText(),
                    "opinion" // tipo
            );
            listPublicaciones.add(publicacion);
            GuardarPublicaciones();
            LimpiarCrearOpinion();
            jTabbedPane1.setSelectedIndex(0);
            ActualizarFeed();
        }
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        if (txtFieldVICosto.getText().trim().isEmpty()
                || txtFieldVIDetalles.getText().trim().isEmpty()
                || txtFieldVILugar.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "¡Debes rellenar todos los campos!");
        } else {
            int id;
            if (listPublicaciones.isEmpty()) {
                id = listPublicaciones.size();
            } else {
                id = listPublicaciones.getLast().getIdPublicacion() + 1;
            }
            Publicacion publicacion = new Publicacion(
                    id,
                    usuarioActual.getIdUsuario(),
                    txtFieldVILugar.getText(),
                    txtFieldVICosto.getText(),
                    txtFieldVIDetalles.getText(),
                    "viaje"
            );
            listPublicaciones.add(publicacion);
            GuardarPublicaciones();
            LimpiarCrearViaje();
            jTabbedPane1.setSelectedIndex(0);
            ActualizarFeed();
        }
    }//GEN-LAST:event_jLabel16MouseClicked

    private void btnUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUsuariosMouseClicked
        new UsuariosFrame().setVisible(true);
    }//GEN-LAST:event_btnUsuariosMouseClicked

    private void labelBtnLugaresPopularesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelBtnLugaresPopularesMouseClicked
        try {
            generarReporteLugares(listPublicaciones, listPreguntas);
        } catch (IOException ex) {
            System.out.println("ERROR AL GENERAR EXCEL");
        }
    }//GEN-LAST:event_labelBtnLugaresPopularesMouseClicked

    private void labelBtnTopUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelBtnTopUsuariosMouseClicked
        try {
            crearPdfUsuariosMasOpiniones();
        } catch (IOException ex) {
            System.out.println("Error con el pdf");
        }
    }//GEN-LAST:event_labelBtnTopUsuariosMouseClicked

    public void ActualizarFeed() {
        CargarPublicaciones();
        panelFeed.removeAll();
        grid.setRows(listPublicaciones.size());
        int cantidadPublicaciones = 0;
        for (Publicacion publicacion : listPublicaciones) {
            boolean valida = false;
            String tipo;
            if (feedIndex == 0) {
                if (publicacion.getTipo().equalsIgnoreCase("opinion")) {
                    valida = true;
                }
            } else if (feedIndex == 1) {
                if (publicacion.getTipo().equalsIgnoreCase("viaje")) {
                    valida = true;
                }
            } else {
                if (publicacion.getIdUsuario() == usuarioActual.getIdUsuario()) {
                    valida = true;
                }
            }

            if (valida) {
                Usuario usuarioPublicacion = obtenerUsuario(publicacion.getIdUsuario());
                if (usuarioPublicacion.isBloqueado() == false) {
                    PanelPublicacion panelPublicacion = new PanelPublicacion(publicacion, usuarioPublicacion, usuarioActual);
                    panelFeed.add(panelPublicacion);
                    cantidadPublicaciones++;
                }
            }
        }
        grid.setRows(cantidadPublicaciones);
        panelFeed.updateUI();
    }

    public void eliminarPublicacion(Publicacion publicacion) {
        listPublicaciones.remove(publicacion);
        GuardarPublicaciones();
        ActualizarFeed();
    }

    public void LimpiarCrearViaje() {
        txtFieldVICosto.setText("");
        txtFieldVIDetalles.setText("");
        txtFieldVILugar.setText("");
    }

    public void LimpiarCrearOpinion() {
        txtFieldOPLugar.setText("");
        txtFielOPEquipaje.setText("");
        txtFielOPLugar1.setText("");
        txtFielOPLugar2.setText("");
        txtFielOPLugar3.setText("");
        txtFielOPObstaculo.setText("");
        txtFielOPPresupuesto.setText("");
        txtFielOPFechas.setText("");
    }

    public void CargarPreguntas() {
        try {
            BufferedReader br = new BufferedReader(
                    new FileReader(ruta + "preguntas.json")
            );
            String lectura = null;
            String resultado = "";
            while ((lectura = br.readLine()) != null) {
                resultado += lectura;
            }
            br.close();

            JSONParser parser = new JSONParser();
            JSONArray jsonArray = (JSONArray) parser.parse(resultado);
            listPreguntas.clear();
            for (int i = 0; i < jsonArray.size(); i++) {
                Pregunta pregunta = new Gson().fromJson(
                        jsonArray.get(i).toString(), Pregunta.class
                );

                listPreguntas.add(pregunta);
            }
        } catch (Exception e) {
            System.out.println("No se cargaron las preguntas del json correctamente");
        }
    }

    public void CargarUsuarios() {
        try {
            BufferedReader br = new BufferedReader(
                    new FileReader(ruta + "usuarios.json")
            );
            String lectura = null;
            String resultado = "";
            while ((lectura = br.readLine()) != null) {
                resultado += lectura;
            }
            br.close();

            JSONParser parser = new JSONParser();
            JSONArray jsonArray = (JSONArray) parser.parse(resultado);
            listUsuarios.clear();
            for (int i = 0; i < jsonArray.size(); i++) {
                Usuario user = new Gson().fromJson(
                        jsonArray.get(i).toString(), Usuario.class
                );

                listUsuarios.add(user);
            }
        } catch (Exception e) {
            System.out.println("No se cargaron los Usuarios del json correctamente");
        }
    }

    public void CargarPublicaciones() {
        try {
            BufferedReader br = new BufferedReader(
                    new FileReader(ruta + "publicaciones.json")
            );
            String lectura = null;
            String resultado = "";
            while ((lectura = br.readLine()) != null) {
                resultado += lectura;
            }
            br.close();

            JSONParser parser = new JSONParser();
            JSONArray jsonArray = (JSONArray) parser.parse(resultado);
            listPublicaciones.clear();
            for (int i = 0; i < jsonArray.size(); i++) {
                Publicacion publicacion = new Gson().fromJson(
                        jsonArray.get(i).toString(), Publicacion.class
                );

                listPublicaciones.add(publicacion);
            }
        } catch (Exception e) {
            System.out.println("No se cargaron las publicaciones del json correctamente");
        }
    }

    public void GuardarPublicaciones() {
        try {
            BufferedWriter bw = new BufferedWriter(
                    new FileWriter(ruta + "publicaciones.json", false)
            );
            String json = new Gson().toJson(listPublicaciones);

            bw.write(json);
            bw.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public Usuario obtenerUsuario(int idUsuario) {
        CargarUsuarios();
        for (Usuario usuario : listUsuarios) {
            if (usuario.getIdUsuario() == idUsuario) {
                return usuario;
            }
        }
        return null; // Retorna null si no se encuentra el usuario
    }

    ///EXCEL Y ARCHIVOS
    public void generarReporteLugares(List<Publicacion> listPublicacion, List<Pregunta> listPreguntas) throws IOException {
        CargarPublicaciones();
        CargarPreguntas();
        Map<String, Integer> conteoLugares = new HashMap<>();

        // Crear una lista de lugares válidos (únicamente los que aparecen en publicaciones)
        Set<String> lugaresValidos = listPublicacion.stream()
                .map(Publicacion::getLugar)
                .collect(Collectors.toSet());

        // Contar menciones de lugares en publicaciones
        for (Publicacion publicacion : listPublicacion) {
            String lugar = publicacion.getLugar();
            conteoLugares.put(lugar, conteoLugares.getOrDefault(lugar, 0) + 1);
        }

        // Contar menciones de lugares en preguntas, solo si la pregunta menciona un lugar válido
        for (Pregunta pregunta : listPreguntas) {
            for (String lugar : lugaresValidos) {
                if (pregunta.getPregunta().contains(lugar)) {
                    conteoLugares.put(lugar, conteoLugares.getOrDefault(lugar, 0) + 1);
                }
            }
        }

        // Ordenar los lugares por número de menciones y seleccionar los tres más mencionados
        List<Map.Entry<String, Integer>> topLugares = conteoLugares.entrySet()
                .stream()
                .sorted(Map.Entry.comparingByValue(Comparator.reverseOrder()))
                .limit(3)
                .collect(Collectors.toList());

        // Generar el archivo Excel y la gráfica
        crearExcelConGrafica(topLugares);
    }

    public void crearExcelConGrafica(List<Map.Entry<String, Integer>> topLugares) throws IOException {
        try (Workbook workbook = new XSSFWorkbook()) {
            // Crear una hoja de Excel
            XSSFSheet sheet = (XSSFSheet) workbook.createSheet("Lugares más mencionados");

            // Crear encabezados
            Row headerRow = sheet.createRow(0);
            headerRow.createCell(0).setCellValue("Lugar");
            headerRow.createCell(1).setCellValue("Menciones");

            // Llenar las filas con los datos de los lugares más mencionados
            int rowNum = 1;
            for (Map.Entry<String, Integer> entry : topLugares) {
                Row row = sheet.createRow(rowNum++);
                row.createCell(0).setCellValue(entry.getKey());
                row.createCell(1).setCellValue(entry.getValue());
            }

            // Crear el gráfico de barras en la hoja
            XSSFDrawing drawing = sheet.createDrawingPatriarch();
            XSSFChart chart = drawing.createChart(drawing.createAnchor(0, 0, 0, 0, 3, 1, 10, 15));

            // Configuración de los ejes
            XDDFCategoryAxis bottomAxis = chart.createCategoryAxis(AxisPosition.BOTTOM);
            bottomAxis.setTitle("Lugares");
            XDDFValueAxis leftAxis = chart.createValueAxis(AxisPosition.LEFT);
            leftAxis.setTitle("Menciones");

            // Crear las fuentes de datos para el gráfico
            XDDFCategoryDataSource lugares = XDDFDataSourcesFactory.fromStringCellRange(sheet, new CellRangeAddress(1, rowNum - 1, 0, 0));
            XDDFNumericalDataSource<Double> menciones = XDDFDataSourcesFactory.fromNumericCellRange(sheet, new CellRangeAddress(1, rowNum - 1, 1, 1));

            // Crear el gráfico de barras (especificamos ChartTypes.BAR)
            XDDFBarChartData data = (XDDFBarChartData) chart.createData(ChartTypes.BAR, bottomAxis, leftAxis);

            // Crear la serie de datos para el gráfico (lugares y menciones)
            XDDFBarChartData.Series series = (XDDFBarChartData.Series) data.addSeries(lugares, menciones);
            series.setTitle("Menciones por Lugar", null);

            // Configurar la dirección de las barras (puedes usar BarDirection.COL para barras verticales)
            data.setBarDirection(BarDirection.COL); // Las barras son verticales

            // Añadir el gráfico de barras a la hoja
            chart.plot(data);

            // Guardar el archivo Excel
            String filePath = ruta + "ReporteLugares.xlsx";
            try (FileOutputStream fileOut = new FileOutputStream(filePath)) {
                workbook.write(fileOut);
            }

            // Abrir automáticamente el archivo Excel
            File file = new File(filePath);
            if (file.exists()) {
                Desktop.getDesktop().open(file);
            }
        }
    }
    

    //PDF
    public void crearPdfUsuariosMasOpiniones() throws IOException {
        CargarPublicaciones();
        CargarUsuarios();
        // Filtrar las publicaciones de tipo "opinión"
        List<Publicacion> publicacionesOpinion = listPublicaciones.stream()
                .filter(pub -> "opinion".equalsIgnoreCase(pub.getTipo()))
                .collect(Collectors.toList());

        // Contar las publicaciones por usuario
        Map<Usuario, Long> publicacionesPorUsuario = publicacionesOpinion.stream()
                .collect(Collectors.groupingBy(
                        pub -> listUsuarios.stream()
                                .filter(user -> user.getIdUsuario() == pub.getIdUsuario())
                                .findFirst()
                                .orElse(null),
                        Collectors.counting()
                ));

        // Obtener los 3 usuarios con más publicaciones de tipo "opinión"
        List<Map.Entry<Usuario, Long>> topUsuarios = publicacionesPorUsuario.entrySet().stream()
                .filter(entry -> entry.getKey() != null)
                .sorted((a, b) -> Long.compare(b.getValue(), a.getValue()))
                .limit(3)
                .collect(Collectors.toList());

        // Crear el documento PDF
        PdfWriter writer = new PdfWriter(ruta + "TopUsuarios.pdf");
        PdfDocument pdf = new PdfDocument(writer);
        Document document = new Document(pdf);

        // Título del documento
        document.add(new Paragraph("Top 3 Usuarios con Más Publicaciones de Opinión").setBold().setFontSize(14));

        // Crear una tabla para los resultados
        Table table = new Table(new float[]{3, 2, 3});
        table.addHeaderCell("Usuario");
        table.addHeaderCell("Total de Publicaciones");
        table.addHeaderCell("Lugar de Publicaciones");

        // Agregar los datos a la tabla
        for (Map.Entry<Usuario, Long> entry : topUsuarios) {
            Usuario usuario = entry.getKey();
            Long totalPublicaciones = entry.getValue();

            // Agregar fila con el nombre del usuario y el total de publicaciones
            table.addCell(usuario.getNombre() + " " + usuario.getApellido());
            table.addCell(totalPublicaciones.toString());

            // Agregar los lugares de cada publicación de tipo "opinión" para el usuario actual
            List<String> lugares = publicacionesOpinion.stream()
                    .filter(pub -> pub.getIdUsuario() == usuario.getIdUsuario())
                    .map(Publicacion::getLugar)
                    .collect(Collectors.toList());

            table.addCell(String.join(", ", lugares));
        }

        // Agregar la tabla al documento
        document.add(table);

        // Cerrar el documento
        document.close();

        // Abrir automáticamente el archivo PDF
        File pdfFile = new File(ruta + "TopUsuarios.pdf");
        if (Desktop.isDesktopSupported()) {
            Desktop.getDesktop().open(pdfFile);
        } else {
            System.out.println("Abrir automáticamente el archivo no es compatible en este sistema.");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CrearOpinion;
    private javax.swing.JPanel CrearViaje;
    private javax.swing.JPanel MenuInicio;
    private org.edisoncor.gui.panel.PanelImage MenuPrincipal;
    private org.edisoncor.gui.panel.PanelImage btnAtras;
    private org.edisoncor.gui.panel.PanelImage btnAtras1;
    private org.edisoncor.gui.panel.PanelImage btnCerrarSesion;
    private org.edisoncor.gui.panel.PanelImage btnCrearOpinion;
    private org.edisoncor.gui.panel.PanelImage btnCrearViaje;
    private org.edisoncor.gui.panel.PanelImage btnLugares;
    private javax.swing.JLabel btnMisPublicaciones;
    private javax.swing.JLabel btnOpiniones;
    private org.edisoncor.gui.panel.PanelImage btnTopus;
    private javax.swing.JLabel btnUsuarios;
    private org.edisoncor.gui.panel.PanelImage btnUsuariosPane;
    private javax.swing.JLabel btnViajes;
    private org.edisoncor.gui.panel.Panel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel labelApellido;
    private javax.swing.JLabel labelBtnLugaresPopulares;
    private javax.swing.JLabel labelBtnTopUsuarios;
    private javax.swing.JLabel labelNombre;
    private org.edisoncor.gui.panel.PanelImage logo;
    private javax.swing.JPanel panelFeed;
    private org.edisoncor.gui.panel.PanelImage panelImage10;
    private org.edisoncor.gui.panel.PanelImage panelImage11;
    private org.edisoncor.gui.panel.PanelImage panelImage2;
    private org.edisoncor.gui.panel.PanelImage panelImage3;
    private org.edisoncor.gui.panel.PanelImage panelImage4;
    private org.edisoncor.gui.panel.PanelImage panelImage5;
    private org.edisoncor.gui.panel.PanelImage panelImage8;
    private org.edisoncor.gui.panel.PanelImage panelImage9;
    private org.edisoncor.gui.panel.PanelImage panelImageMisPublicacionesBtn;
    private org.edisoncor.gui.panel.PanelImage panelImageOpinionBtn;
    private org.edisoncor.gui.panel.PanelImage panelImageViajesBtn;
    private javax.swing.JScrollPane scrollPrincipal;
    private javax.swing.JTextArea txtFielOPEquipaje;
    private javax.swing.JTextArea txtFielOPFechas;
    private javax.swing.JTextField txtFielOPLugar1;
    private javax.swing.JTextField txtFielOPLugar2;
    private javax.swing.JTextField txtFielOPLugar3;
    private javax.swing.JTextArea txtFielOPObstaculo;
    private javax.swing.JTextField txtFielOPPresupuesto;
    private javax.swing.JTextField txtFieldOPLugar;
    private javax.swing.JTextField txtFieldVICosto;
    private javax.swing.JTextArea txtFieldVIDetalles;
    private javax.swing.JTextField txtFieldVILugar;
    // End of variables declaration//GEN-END:variables
}
