
package com.mycompany.triptalk;

import com.google.gson.Gson;
import com.mycompany.triptalk.clases.Pregunta;
import com.mycompany.triptalk.clases.Publicacion;
import com.mycompany.triptalk.clases.Usuario;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.util.ArrayList;
import org.json.simple.JSONArray;
import org.json.simple.parser.JSONParser;

public class PanelPregunta extends javax.swing.JPanel {
    
    private Pregunta pregunta;
    private Usuario usuarioActual;
    private ArrayList<Usuario> listUsuarios = new ArrayList<>();
    private ArrayList<Publicacion> listPublicaciones = new ArrayList<>();
    
    private String ruta = "C:\\Users\\arman\\Instituto Tecnológico de Morelia\\DANIEL ADRIAN ROQUE CORTES - Red social de sugerencia de viajes\\Files\\";
    
    public PanelPregunta() {
        initComponents();
    }
    
    public PanelPregunta(Pregunta pregunta, Usuario usuarioActual) {
        initComponents();
        this.pregunta=pregunta;
        this.usuarioActual=usuarioActual;
        ActualizarInfo();
    }
    
    public void ActualizarInfo(){
        
        
    }
    
    public void CargarUsuarios(){
        try {
            BufferedReader br = new BufferedReader(
                new FileReader(ruta+"usuarios.json")
            );
            String lectura=null;
            String resultado="";
            while((lectura=br.readLine()) != null){
                resultado +=lectura;
            }
            br.close();

            JSONParser parser = new JSONParser();
            JSONArray jsonArray = (JSONArray)parser.parse(resultado);
            listUsuarios.clear();
            for (int i = 0; i < jsonArray.size(); i++) {
                Usuario user = new Gson().fromJson(
                    jsonArray.get(i).toString(), Usuario.class
                );

                listUsuarios.add(user);
            }
        } catch (Exception e) {
            System.out.println("No se cargaron los Usuarios del json correctamente");
        }
    }
    
    public void CargarPublicaciones(){
        try {
            BufferedReader br = new BufferedReader(
                new FileReader(ruta+"publicaciones.json")
            );
            String lectura=null;
            String resultado="";
            while((lectura=br.readLine()) != null){
                resultado +=lectura;
            }
            br.close();

            JSONParser parser = new JSONParser();
            JSONArray jsonArray = (JSONArray)parser.parse(resultado);
            listPublicaciones.clear();
            for (int i = 0; i < jsonArray.size(); i++) {
                Publicacion publicacion = new Gson().fromJson(
                    jsonArray.get(i).toString(), Publicacion.class
                );

                listPublicaciones.add(publicacion);
            }
        } catch (Exception e) {
            System.out.println("No se cargaron las publicaciones del json correctamente");
        }
    }
    
    public void GuardarPublicaciones(){
        try {
            BufferedWriter bw = new BufferedWriter(
                new FileWriter(ruta+"publicaciones.json",false)
            );
            String json = new Gson().toJson(listPublicaciones);
            
            bw.write(json);
            bw.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    public Usuario obtenerUsuario(int idUsuario) {
        CargarUsuarios();
        for (Usuario usuario : listUsuarios) {
            if (usuario.getIdUsuario() == idUsuario) {
                return usuario;
            }
        }
        return null; // Retorna null si no se encuentra el usuario
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelImage1 = new org.edisoncor.gui.panel.PanelImage();
        labelNombre = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPaneComentario = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        txtFieldResponder = new javax.swing.JTextField();
        panelImage2 = new org.edisoncor.gui.panel.PanelImage();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/panelBlancoRedondeado.png"))); // NOI18N
        panelImage1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelNombre.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        labelNombre.setForeground(new java.awt.Color(255, 153, 51));
        labelNombre.setText("jLabel1");
        panelImage1.add(labelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 15, 465, 19));

        txtPaneComentario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtPaneComentario.setForeground(new java.awt.Color(204, 102, 0));
        txtPaneComentario.setText("Esto es un ejemplo de pregunta");
        jScrollPane1.setViewportView(txtPaneComentario);

        panelImage1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 46, 607, 73));

        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("Respuestas:    Escribe una respuesta al comentario");
        panelImage1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 127, 544, 20));

        txtFieldResponder.setBackground(new java.awt.Color(255, 204, 153));
        txtFieldResponder.setForeground(new java.awt.Color(255, 255, 255));
        panelImage1.add(txtFieldResponder, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 510, -1));

        panelImage2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/barraNaranja.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Enviar");

        javax.swing.GroupLayout panelImage2Layout = new javax.swing.GroupLayout(panelImage2);
        panelImage2.setLayout(panelImage2Layout);
        panelImage2Layout.setHorizontalGroup(
            panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
        );
        panelImage2Layout.setVerticalGroup(
            panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
        );

        panelImage1.add(panelImage2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 230, -1, 22));

        jTextPane1.setEditable(false);
        jScrollPane3.setViewportView(jTextPane1);

        panelImage1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 610, 69));

        add(panelImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 280));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JLabel labelNombre;
    private org.edisoncor.gui.panel.PanelImage panelImage1;
    private org.edisoncor.gui.panel.PanelImage panelImage2;
    private javax.swing.JTextField txtFieldResponder;
    private javax.swing.JTextPane txtPaneComentario;
    // End of variables declaration//GEN-END:variables
}
